fix: image download (DEV-4321) (DEV-4318)
dasch-swiss/dsp-app pull request #1885
Opened 2024-11-12 10:56 UTC by irmastnt

resolves DEV-4321, DEV-4318

2024-11-12 14:17 UTC, domsteinbach requested changes
The compound viewer does not pass any attachedProject to the image components. I also would prefer to get the attached project by a state.

2024-11-12 14:17 UTC, domsteinbach commented on libs/vre/shared/app-representations/src/lib/still-image/still-image-toolbar.component.ts
> +    const projectShort = this.attachedProject?.shortcode;
in case of the compound view it is always undefined.

2024-11-12 14:17 UTC, domsteinbach commented on libs/vre/shared/app-representations/src/lib/still-image/still-image.component.ts
> +        [attachedProject]="attachedProject"
in case of the compound viewer always undefined

2024-11-12 18:27 UTC, irmastnt commented
> The compound viewer does not pass any attachedProject to the image components. I also would prefer to get the attached project by a state.

Should be ok now

2024-11-19 14:10 UTC, domsteinbach approved these changes

2024-11-19 14:39 UTC, merged