chore(cookie-policy): reactivate the cookie policy banner (DSP-1727)
dasch-swiss/dsp-app pull request #461
Opened 2021-06-10 13:04 UTC by kilchenmann

resolves DSP-1727

2021-06-10 13:05 UTC, kilchenmann commented
The "history back" button doesn't work anymore. Will fix it...

2021-06-11 07:47 UTC, mdelez requested changes
I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.

2021-06-11 07:47 UTC, mdelez commented on src/app/app.component.html
> +            This web-application uses cookies to provide you with great user experience. By using the application you
with a greater user experience

2021-06-11 08:10 UTC, kilchenmann commented
> I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.

But what should happen, when the user click on "reject"? Redirect the user to a google page? Because in this case s/he can't use the app. 
This is anyway a temporary solution only. Daniela and Marchin are working on a better implementation, where the user can select which cookies should be enabled.

2021-06-11 08:13 UTC, kilchenmann commented on src/app/app.component.html
> +            This web-application uses cookies to provide you with great user experience. By using the application you
rewritten in fd2ecf2

2021-06-11 08:38 UTC, mdelez commented
> > I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.
> 
> But what should happen, when the user click on "reject"? Redirect the user to a google page? Because in this case s/he can't use the app.
> This is anyway a temporary solution only. Daniela and Marchin are working on a better implementation, where the user can select which cookies should be enabled.

The website should still be useable even if the user rejected all **non-essential** cookies. We can still use cookie that are essential to the website operating. The user just needs to be allowed the reject any cookie that may have identifying data. https://gdpr.eu/cookies/#:~:text=To%20comply%20with%20the%20regulations,cookies%20except%20strictly%20necessary%20cookies.&text=Allow%20users%20to%20access%20your,the%20use%20of%20certain%20cookies

2021-06-11 09:06 UTC, kilchenmann commented
> > > I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.
> > 
> > 
> > But what should happen, when the user click on "reject"? Redirect the user to a google page? Because in this case s/he can't use the app.
> > This is anyway a temporary solution only. Daniela and Marchin are working on a better implementation, where the user can select which cookies should be enabled.
> 
> The website should still be useable even if the user rejected all **non-essential** cookies. We can still use cookie that are essential to the website operating. The user just needs to be allowed the reject any cookie that may have identifying data. https://gdpr.eu/cookies/#:~:text=To%20comply%20with%20the%20regulations,cookies%20except%20strictly%20necessary%20cookies.&text=Allow%20users%20to%20access%20your,the%20use%20of%20certain%20cookies

Yes I know and you're right, but in DSP-APP we have only **essential** cookies (the one for the login). When the user reject them s/he can't use the app. This is why I wrote: "If you want to use the app, you have to accept the cookie policy".

2021-06-11 09:09 UTC, mdelez commented
> > > > I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.
> > > 
> > > 
> > > But what should happen, when the user click on "reject"? Redirect the user to a google page? Because in this case s/he can't use the app.
> > > This is anyway a temporary solution only. Daniela and Marchin are working on a better implementation, where the user can select which cookies should be enabled.
> > 
> > 
> > The website should still be useable even if the user rejected all **non-essential** cookies. We can still use cookie that are essential to the website operating. The user just needs to be allowed the reject any cookie that may have identifying data. https://gdpr.eu/cookies/#:~:text=To%20comply%20with%20the%20regulations,cookies%20except%20strictly%20necessary%20cookies.&text=Allow%20users%20to%20access%20your,the%20use%20of%20certain%20cookies
> 
> Yes I know and you're right, but in DSP-APP we have only **essential** cookies (the one for the login). When the user reject them s/he can't use the app. This is why I wrote: "If you want to use the app, you have to accept the cookie policy".

That's fair. So then at that point I don't think we even need a cookies banner. You could also just add a "Reject non-essential cookies" button that does nothing but dismiss the banner since we don't have any non-essential cookies.

2021-06-11 09:15 UTC, kilchenmann commented
> > > > > I think there needs to be a "Reject" button as well, no? There is currently no way to dismiss the banner besides clicking the "Accept" button.
> > > > 
> > > > 
> > > > But what should happen, when the user click on "reject"? Redirect the user to a google page? Because in this case s/he can't use the app.
> > > > This is anyway a temporary solution only. Daniela and Marchin are working on a better implementation, where the user can select which cookies should be enabled.
> > > 
> > > 
> > > The website should still be useable even if the user rejected all **non-essential** cookies. We can still use cookie that are essential to the website operating. The user just needs to be allowed the reject any cookie that may have identifying data. https://gdpr.eu/cookies/#:~:text=To%20comply%20with%20the%20regulations,cookies%20except%20strictly%20necessary%20cookies.&text=Allow%20users%20to%20access%20your,the%20use%20of%20certain%20cookies
> > 
> > 
> > Yes I know and you're right, but in DSP-APP we have only **essential** cookies (the one for the login). When the user reject them s/he can't use the app. This is why I wrote: "If you want to use the app, you have to accept the cookie policy".
> 
> That's fair. So then at that point I don't think we even need a cookies banner. You could also just add a "Reject non-essential cookies" button that does nothing but dismiss the banner since we don't have any non-essential cookies.

As Subotic said yesterday, I should reactivate the banner. So that's what I did.

2021-06-11 13:12 UTC, mdelez approved these changes

2021-06-11 13:21 UTC, kilchenmann commented
Thank you @mdelez

2021-06-11 13:21 UTC, merged