feat!: display dsp release number (DEV-420)
dasch-swiss/dsp-app pull request #644
Opened 2022-01-30 14:43 UTC by kilchenmann

resolves DEV-420

This PR contains a breaking change because it needs an updated version of the configuration.

2022-02-01 13:31 UTC, kilchenmann commented
@mdelez I've attached the screenshots of the app in different environments directly to the jira-task description.

2022-02-02 08:55 UTC, mdelez requested changes
Works well for me! Just some things to clean up :)

2022-02-02 08:55 UTC, mdelez commented on src/app/main/header/header.component.html
> +            <!-- environment info-text {{dsp.color}}" [class.strong]="!dsp.production"> -->
can this be removed?

2022-02-02 08:55 UTC, mdelez commented on src/app/main/header/header.component.ts
> +// const { version: appVersion } = require('../../../../package.json');
this can also be removed I'm guessing

2022-02-02 09:31 UTC, kilchenmann commented on src/app/main/header/header.component.html
> +            <!-- environment info-text {{dsp.color}}" [class.strong]="!dsp.production"> -->
done in 65607173

2022-02-02 09:31 UTC, kilchenmann commented on src/app/main/header/header.component.ts
> +// const { version: appVersion } = require('../../../../package.json');
done in 65607173

2022-02-02 09:35 UTC, mdelez approved these changes
Thank you for this, it's super helpful!

2022-02-02 09:37 UTC, merged