docs: Add documentation about the different file types and their functionalities
dasch-swiss/dsp-app pull request #804
Opened 2022-08-22 15:01 UTC by flavens

resolves DEV-1200

2022-08-29 12:05 UTC, mdelez requested changes

2022-08-29 12:05 UTC, mdelez commented on docs/user-guide/data.md
> +Supported format: **mp4**
"supported file types" instead of "supported format"

2022-08-29 12:05 UTC, mdelez commented on docs/user-guide/data.md
> +Supported format: **zip**, **x-tar**, **gzip**
After #808 is merged, the supported **file types** (should change from "supported format") will be zip, tar, gz, gzip, 7z, tgz, z

2022-08-29 12:05 UTC, mdelez commented on docs/user-guide/data.md
> +When you open a resource that contains an image, this one is displayed in a viewer. Several functionalities are accessible from the image viewer, e.g. zoom in/out, copy the IIIF link, replace the ima
"this one" -> "it"

2022-08-30 09:06 UTC, flavens commented
@mdelez FYI I added a small change requested by Marion (dev-1272)

2022-08-30 09:12 UTC, mdelez commented on docs/user-guide/data.md
> +DSP-APP offers different resource views for different media types (images, videos, audio, archives, text, and PDF files). You can access to the resources from the list of search results. Depending on
You can access ~~to~~ the resources

2022-08-30 09:54 UTC, mdelez approved these changes

2022-08-30 09:59 UTC, merged