docs: Reorganise the main menu and the data menu
dasch-swiss/dsp-app pull request #807
Opened 2022-08-24 14:52 UTC by flavens

resolves DEV-1258

2022-08-24 14:54 UTC, flavens commented
@mdelez I cannot display the left-side menu as a drop-down menu like the one in DSP-API. Any idea about the syntax I should use?

2022-08-24 15:19 UTC, flavens commented on mkdocs.yml
> -    - navigation.sections
To display the left side menu with a drop-down, I removed this line. It is the only way I found to do what I wanted.
Open to any other suggestions.

2022-08-30 12:08 UTC, flavens commented
@mdelez I resolved the conflicts. Possible to review when you can.

2022-08-31 07:57 UTC, mdelez requested changes

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/search.md
> +The full-text search performs queries including one or more terms or phrases and returns data that matches search conditions. By default, the search is performed in all projects stored in DSP. Howeve
The full-text search performs queries including one or more terms or phrases and returns data that matches **the** search conditions. By default, the search is performed in all projects stored in DSP. However, it is possible to filter by ~~the~~ project using the ~~menu~~ "Filter by project" **menu** on the left side of the search bar.

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/search.md
> +When clicking on the search bar, the search history panel is displayed. The **10** last searches are registered. It is also possible to clear the search history list (*Clear list* button at the botto
the 10 last -> the last 10

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +DSP-APP offers different resource views for different media types (images, videos, audio, archives, text, and PDF files). You can access the resources from the list of search results. Depending on th
PDF files -> document files

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +If your property is linked to another resource, you can search for an existing value by typing the first letter of the resource label you are looking for. You can also create a new resource instance
the first **three** letters

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +To edit the resource label, you reach the edit form by opening the resource menu on the right-side of the toolbar and clicking on `Edit label`.
To edit the resource label, ~~you reach the edit form by opening~~ **open** the resource menu on the right-side of the toolbar and ~~clicking~~ **click** on `Edit label`.

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +To get more information about the property value, i.e. date of creation and author name, you mouse over the value and then on the info button.
~~you mouse~~ **hover** over the value and then ~~on~~ **over** the info button.

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +To display the existing value comment, you mouse over the property value and click on the comment button (3rd icon from the left).
you mouse -> hover

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +![Mouse over the property value to see if there is a comment.](../../assets/images/comment-value.png)*Mouse over the property value to see if there is a comment and display it.*
Mouse -> Hover

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +To create a new region on an image, you click on the button Draw a region in the toolbar, then select the region you want on the image.
Draw a region -> "Draw a region"

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +You can edit a property value from the resource viewer. You mouse over the value and click on the edit button.
You mouse -> Hover

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +2. **Erase** resource: the resource is **definitely** deleted from the database, it will be impossible to get it back.
definitely -> permanently

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +You can delete a property value. You mouse over the value and click on the delete button. You have to confirm your choice. It is possible to comment on the deletion of the value in the confirmation p
You mouse -> Hover

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +Go to your resource B. You click on the **edit** button of the property value where you want to add the link (by mousing over the value content). This value must be of type **rich text**.
mousing -> hovering

2022-08-31 07:57 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +Each resource of your dataset gets an ARK URL (Archival Resource Key), a persistent identifier that will allow citing permanently your resource in papers, conference presentations, books, etc.
citing permanently -> you to permanently cite

2022-09-01 07:37 UTC, mdelez requested changes
just one small fix and then I will approve

2022-09-01 07:37 UTC, mdelez commented on docs/user-guide/data/work-on-data.md
> +If your property is linked to another resource, you can search for an existing value by typing the first three letter of the resource label you are looking for. You can also create a new resource ins
letter -> letters

2022-09-09 10:02 UTC, mdelez approved these changes

2022-09-09 10:02 UTC, merged