fix: Ontologies displayed twice (DEV-1325)
dasch-swiss/dsp-app pull request #832
Opened 2022-09-22 12:46 UTC by EricSommerhalder

resolves DEV-1325

2022-09-22 12:58 UTC, mdelez requested changes

2022-09-22 12:58 UTC, mdelez commented on src/app/project/ontology/ontology.component.ts
> +                const temp: ReadOntology[] = [];
I would rename these temp variables to something a bit more meaningful

2022-09-22 12:58 UTC, mdelez commented on src/app/project/ontology/ontology.component.ts
> +import { O } from '@angular/cdk/keycodes';
auto-import FTW?

2022-09-22 13:02 UTC, EricSommerhalder commented on src/app/project/ontology/ontology.component.ts
> +import { O } from '@angular/cdk/keycodes';
got to love it

2022-09-23 07:31 UTC, mdelez approved these changes
works well, thanks :)

2022-09-23 07:31 UTC, merged