refactor: project IRI refactor (DEV-1468)
dasch-swiss/dsp-app pull request #862
Opened 2022-11-01 10:15 UTC by mdelez

resolves DEV-1468

2022-11-09 15:14 UTC, mdelez commented
A quick rundown of the changes I've made (whoever would like to review should sit down with me so I can better explain):

- switch from using `getXXXByShortcode` to `getXXXByProjectIri`
- change the routing to use `uuid` instead of `shortcode`
- adds new methods to `ProjectService` to construct project IRIs and extract UUIDs from a project IRI
- lots of changes to test files

2022-11-11 12:13 UTC, mpro7 requested changes
Pushed changes look good. Feel free to implement my suggestions.

I think there are still some instances of old project IRI with shortcode in the repo. To find them just search for `projects/0`. Most probably there are no other shorcodes used on the APP.

2022-11-17 08:59 UTC, mdelez commented on src/app/main/dialog/dialog.component.html
> +        <app-project-form [projectIri]="data.project" (closeDialog)="dialogRef.close()"></app-project-form>
`projectIri` is correct here, I could simply pass the `projectUuid` instead but then I would need to rebuild the IRI which I've already built.

2022-11-17 09:09 UTC, mdelez commented on src/app/project/list/list.component.ts
>          }
changed to a one liner in [4e8f9a4](https://github.com/dasch-swiss/dsp-app/pull/862/commits/4e8f9a44cd25579016bb840ce107340c03b544bb)

2022-11-17 09:09 UTC, mdelez commented on src/app/project/ontology/ontology.component.ts
>          }
changed to a one liner in [4e8f9a4](https://github.com/dasch-swiss/dsp-app/pull/862/commits/4e8f9a44cd25579016bb840ce107340c03b544bb)

2022-11-17 10:48 UTC, mpro7 commented on src/app/project/list/list.component.ts
>          }
Thanks, was thinking more to use template literals instead of pure concatenation, but it looks better anyway.

2022-11-17 10:52 UTC, mdelez commented
> Pushed changes look good. Feel free to implement my suggestions.
> 
> I think there are still some instances of old project IRI with shortcode in the repo. To find them just search for `projects/0`. Most probably there are no other shorcodes used on the APP.

I checked and there are no matches for "projects/0"
there are some places where shortcodes are still used but it's for lists and such

2022-11-18 07:27 UTC, mpro7 approved these changes

2022-12-07 12:09 UTC, merged