style(side-nav): redesign of side navigator (2)
dasch-swiss/dsp-app pull request #877
Opened 2022-11-24 07:50 UTC by Vijeinath

resolves DEV-1454

2022-11-28 15:51 UTC, mdelez requested changes
It's looking pretty good! Just a few small things:
<img width="413" alt="Screen Shot 2022-11-28 at 16 28 23" src="https://user-images.githubusercontent.com/60604010/204320476-81c6e9b5-f6bb-46a4-b893-ba9860c8273d.png">

When hovering over a class item, the edges of the left side of the box aren't rounded. It would look nicer if they were.

<img width="280" alt="Screen Shot 2022-11-28 at 16 36 26" src="https://user-images.githubusercontent.com/60604010/204321212-8ca82a73-0c99-4298-8620-6349cd211425.png">

This was an issue before but it would also look better if the arrow was vertically aligned with the label.

One thing seems to have been overlooked which is the "Left Menu in a closed state" part of the [confluence page](https://dasch.atlassian.net/wiki/spaces/E/pages/122486785/Overview+and+Requirements+Data+Browser+Workspace#Changes-to-the-left-sidebar). Idk how easy of a task this is so many it's better as a separate PR.

2022-11-28 15:51 UTC, mdelez commented on src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss
> +  .v-content {
what does "v" mean?

2022-11-28 15:51 UTC, mdelez commented on src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
> +    trimLabel(fullString: string) {
Interesting! I suppose since the width is fixed, this isn't a problem with responsiveness.

2022-11-29 07:57 UTC, Vijeinath commented on src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss
> +  .v-content {
Forgot to change it back

2022-11-29 11:16 UTC, Vijeinath commented
@mdelez
Regarding "Left Menu in a closed state": I actually tried to implement it but it seems like a big css refactoring is needed.

2022-11-30 10:21 UTC, mdelez commented
> @mdelez Regarding "Left Menu in a closed state": I actually tried to implement it but it seems like a big css refactoring is needed. For that reason I left it out.

No problem. I've adjusted the Jira story and made a new [story](https://dasch.atlassian.net/browse/DEV-1535) just for that functionality.

2022-11-30 10:24 UTC, mdelez approved these changes
thanks!

2022-11-30 11:43 UTC, merged