feat(cardinalities): implement cardinalities user workflow (Dev-1615 )
dasch-swiss/dsp-app pull request #917
Opened 2023-02-13 10:28 UTC by domsteinbach

resolves DEV-1615

2023-02-13 16:17 UTC, Vijeinath approved these changes
Good!

2023-02-14 08:25 UTC, mdelez requested changes

2023-02-14 08:25 UTC, mdelez commented on src/app/project/ontology/property-form/property-form.component.spec.ts
> -@Component({ selector: 'app-string-literal-input', template: '' })
In https://github.com/dasch-swiss/dsp-app/pull/893 we spent a lot of time decluttering the unit test logs. This mock component should remain as without it we get spam in the logs again.

<img width="897" alt="Screen Shot 2023-02-14 at 08 57 30" src="https://user-images.githubusercontent.com/60604010/218677687-07d1056c-8a7e-455e-96ff-f0812e720ea9.png">

2023-02-14 12:09 UTC, mdelez approved these changes

2023-02-14 17:21 UTC, merged